# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Tracking Poverty
tagline:          ''
description:      'Building Households and Families out of Individual Level Administrative Data' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2022-Tracking-Poverty"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2022-Tracking-Poverty/
